version: '{build}'

configuration:
  - Debug
  - Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: "Visual Studio 15 2017"

matrix:
  fast_finish: true
  

install:
  # git bash conflicts with MinGW makefiles
  - if "%CMAKE_GENERATOR%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%CXX_PATH%"=="" (set "PATH=%PATH%;%CXX_PATH%")
  - git submodule update --init --recursive


build_script:
  - md _build -Force
  - cd _build
  - echo %configuration%
  - cmake -G "%CMAKE_GENERATOR%" "-DCMAKE_BUILD_TYPE=%configuration%" -DBUILD_TESTING=ON ..
  - cmake --build . --config %configuration%

